version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - pos-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: pos-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pos-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: pos-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pos_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: pos_user
    volumes:
      - pos_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pos-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pos-network
    depends_on:
      - app

volumes:
  pos_db_data:

networks:
  pos-network:
    driver: bridge